# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CuriosSwift' do

pod 'Alamofire', '~> 1.2.3'
pod 'Kingfisher', '~> 1.4.2'
pod 'Mantle', '~> 2.0'
pod 'MJExtension'
pod 'DateTools'
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
#pod 'Realm', '~> 0.91.3'
pod 'pop', '~> 1.0.7'
pod 'SnapKit', '~> 0.10.0'
pod 'Qiniu', '~> 7.0'
pod 'SVProgressHUD'
pod 'MJRefresh', '~> 2.2.0'
pod 'AsyncDisplayKit'

end

target 'CuriosSwiftTests' do

end

