# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'CuriosSwift' do

pod 'Alamofire', '~> 1.2.0'
pod 'Kingfisher', '~> 1.1.1'
pod 'Mantle', '~> 2.0'
#pod 'Realm', '~> 0.91.3'
pod 'pop', '~> 1.0.7'

end

target 'CuriosSwiftTests' do

end

