//
//  CuriosKit.swift
//  Curios
//
//  Created by Emiaostein on 6/2/15.
//  Copyright (c) 2015 Botai Technology. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CuriosKit : NSObject {

    //// Drawing Methods

    public class func drawControlPannel(#frame: CGRect) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(frame.minX + 0.5, frame.minY + 0.5, frame.width - 1, frame.height - 1))
        UIColor.redColor().setStroke()
        rectanglePath.lineWidth = 1
        CGContextSaveGState(context)
        CGContextSetLineDash(context, 0, [5, 2], 2)
        rectanglePath.stroke()
        CGContextRestoreGState(context)


        //// Oval Drawing
//        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + frame.width - 23, frame.minY + frame.height - 24, 44, 44))
//        UIColor.grayColor().setFill()
//        ovalPath.fill()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
